feat(ckb): ckb multi sign support
nervosnetwork/force-bridge pull request #41
Opened 2021-04-18 16:25 UTC by LeonLi000

2021-04-21 08:10 UTC, solargatsby commented on docker/docker.log
> +Attaching to docker_btc_1, docker_mysql_1, docker_geth_1, docker_ckb_1, docker_ckb-indexer_1
This file and .docker.log.swp should not be committed

2021-04-21 08:33 UTC, solargatsby commented on offchain-modules/src/packages/ckb/tx-helper/generator.ts
> +  // async mint(userLockscript: Script, records: MintAssetRecord[]): Promise<CKBComponents.RawTransactionToSign> {
remove useless  code

2021-04-21 08:37 UTC, solargatsby commented on offchain-modules/src/packages/ckb/tx-helper/multisig/deploy.ts
> +const indexer = new Indexer('http://127.0.0.1:8114', dataDir);
Don't use magic number in code

2021-04-21 08:37 UTC, solargatsby commented on offchain-modules/src/packages/ckb/tx-helper/multisig/deploy.ts
> +  const ckbRpc = new RPC('http://127.0.0.1:8114');
Don't use magic number in code

2021-04-21 08:44 UTC, solargatsby commented on offchain-modules/src/packages/handlers/ckb.ts
> +    console.log('signingEntries length:', txSkeleton.get('signingEntries').size);
using logger

2021-04-21 08:44 UTC, solargatsby commented on offchain-modules/src/packages/handlers/ckb.ts
> +    console.log('tx:', JSON.stringify(tx, null, 2));
using logger

2021-04-21 08:44 UTC, solargatsby commented on offchain-modules/src/packages/handlers/ckb.ts
> +        console.log('tx:', JSON.stringify(tx, null, 2));
using logger

2021-04-27 10:37 UTC, huwenchao commented on offchain-modules/src/packages/ckb/tx-helper/generator.ts
> +const infos = require('./multisig/infos.json');
why not put it into config?

2021-04-27 10:40 UTC, huwenchao commented on offchain-modules/src/packages/ckb/tx-helper/generator.ts
> +  async fetchBridgeCell(bridgeLock: any, indexer: Indexer, maxTimes: number): Promise<Cell> {
why `bridgeLock: any` here? seems like it can only be Lockscript Type.

2021-04-29 03:08 UTC, huwenchao commented on docker/docker.log
> +Attaching to docker_mysql_1, docker_geth_1, docker_btc_1, docker_ckb_1, docker_ckb-indexer_1
should be deleted

2021-04-29 13:52 UTC, mkxbl requested changes

2021-04-29 13:52 UTC, mkxbl commented on offchain-modules/src/packages/ckb/tx-helper/generator.ts
> +    }
should delete `add pwLock.cellDep` code, because this was already added in frontend

2021-05-06 08:29 UTC, LeonLi000 commented on offchain-modules/src/packages/core.ts
> +    // ForceBridgeCore.indexer.startForever();
Because ForceBridgeCore will also be initialized in the integration test

2021-05-06 08:32 UTC, LeonLi000 commented on offchain-modules/src/scripts/integration-test/eos.ts
> -  const PRI_KEY = ForceBridgeCore.config.ckb.privateKey;
the private key is used to sign burn transaction.

2021-05-12 18:53 UTC, closed without merging